# Generated by Django 3.2.2 on 2023-04-15 10:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('position', models.CharField(choices=[('PG', 'PG'), ('SG', 'SG'), ('SF', 'SF'), ('PF', 'PF'), ('C', 'C')], max_length=2)),
                ('games_played', models.IntegerField()),
                ('points_per_game', models.FloatField()),
                ('rebounds_per_game', models.FloatField()),
                ('assists_per_game', models.FloatField()),
                ('steals_per_game', models.FloatField()),
                ('blocks_per_game', models.FloatField()),
                ('fieldgoals_per_game', models.FloatField()),
                ('three_point_field_goal_percentage', models.FloatField()),
                ('free_throw_percentage', models.FloatField()),
            ],
        ),
    ]
