# Generated by Django 3.2.2 on 2023-04-17 18:38

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default='01-01-2000 00:00:00')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('games_played', models.IntegerField(default=0)),
                ('points_per_game', models.FloatField(default=0)),
                ('rebounds_per_game', models.FloatField(default=0)),
                ('assists_per_game', models.FloatField(default=0)),
                ('steals_per_game', models.FloatField(default=0)),
                ('blocks_per_game', models.FloatField(default=0)),
                ('fieldgoals_per_game', models.FloatField(default=0)),
                ('three_point_field_goal_percentage', models.FloatField(default=0)),
                ('free_throw_percentage', models.FloatField(default=0)),
            ],
        ),
    ]
