# Generated by Django 3.2.2 on 2023-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketballapp430', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='assists_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocks_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='fieldgoals_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='free_throw_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebounds_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='steals_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='three_point_field_goal_percentage',
            field=models.FloatField(default=0),
        ),
    ]
